"""Add Health, AI, and Shop Models

Revision ID: 10e1f6f86625
Revises: b4_pets_0003
Create Date: 2026-07-15 20:15:02.301957

"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '10e1f6f86625'
down_revision: Union[str, None] = 'b4_pets_0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['shop_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_categories_created_at'), 'shop_categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_shop_categories_name'), 'shop_categories', ['name'], unique=True)
    op.create_index(op.f('ix_shop_categories_slug'), 'shop_categories', ['slug'], unique=True)
    op.create_index(op.f('ix_shop_categories_updated_at'), 'shop_categories', ['updated_at'], unique=False)
    op.create_table('shop_carts',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_carts_created_at'), 'shop_carts', ['created_at'], unique=False)
    op.create_index(op.f('ix_shop_carts_updated_at'), 'shop_carts', ['updated_at'], unique=False)
    op.create_index(op.f('ix_shop_carts_user_id'), 'shop_carts', ['user_id'], unique=True)
    op.create_table('shop_orders',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'PACKED', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus', native_enum=False, length=20), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_orders_created_at'), 'shop_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_shop_orders_status'), 'shop_orders', ['status'], unique=False)
    op.create_index(op.f('ix_shop_orders_updated_at'), 'shop_orders', ['updated_at'], unique=False)
    op.create_index(op.f('ix_shop_orders_user_id'), 'shop_orders', ['user_id'], unique=False)
    op.create_table('shop_products',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('ingredients', sa.JSON(), nullable=True),
    sa.Column('nutrition', sa.JSON(), nullable=True),
    sa.Column('pet_types', sa.JSON(), nullable=True),
    sa.Column('breed_support', sa.JSON(), nullable=True),
    sa.Column('age_support', sa.JSON(), nullable=True),
    sa.Column('medical_tags', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['shop_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_products_brand'), 'shop_products', ['brand'], unique=False)
    op.create_index(op.f('ix_shop_products_category_id'), 'shop_products', ['category_id'], unique=False)
    op.create_index(op.f('ix_shop_products_created_at'), 'shop_products', ['created_at'], unique=False)
    op.create_index(op.f('ix_shop_products_name'), 'shop_products', ['name'], unique=False)
    op.create_index(op.f('ix_shop_products_updated_at'), 'shop_products', ['updated_at'], unique=False)
    op.create_table('shop_wishlists',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_wishlists_created_at'), 'shop_wishlists', ['created_at'], unique=False)
    op.create_index(op.f('ix_shop_wishlists_updated_at'), 'shop_wishlists', ['updated_at'], unique=False)
    op.create_index(op.f('ix_shop_wishlists_user_id'), 'shop_wishlists', ['user_id'], unique=True)
    op.create_table('ai_conversations',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('context_snapshot', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_created_at'), 'ai_conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_conversations_pet_id'), 'ai_conversations', ['pet_id'], unique=False)
    op.create_index(op.f('ix_ai_conversations_updated_at'), 'ai_conversations', ['updated_at'], unique=False)
    op.create_index(op.f('ix_ai_conversations_user_id'), 'ai_conversations', ['user_id'], unique=False)
    op.create_table('health_documents',
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_documents_created_at'), 'health_documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_health_documents_pet_id'), 'health_documents', ['pet_id'], unique=False)
    op.create_index(op.f('ix_health_documents_updated_at'), 'health_documents', ['updated_at'], unique=False)
    op.create_table('medical_records',
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('diagnosis', sa.String(length=255), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_records_created_at'), 'medical_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_medical_records_pet_id'), 'medical_records', ['pet_id'], unique=False)
    op.create_index(op.f('ix_medical_records_updated_at'), 'medical_records', ['updated_at'], unique=False)
    op.create_table('medications',
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('medicine_name', sa.String(length=255), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_created_at'), 'medications', ['created_at'], unique=False)
    op.create_index(op.f('ix_medications_pet_id'), 'medications', ['pet_id'], unique=False)
    op.create_index(op.f('ix_medications_updated_at'), 'medications', ['updated_at'], unique=False)
    op.create_table('shop_cart_items',
    sa.Column('cart_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['shop_carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['shop_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_cart_items_cart_id'), 'shop_cart_items', ['cart_id'], unique=False)
    op.create_index(op.f('ix_shop_cart_items_created_at'), 'shop_cart_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_shop_cart_items_product_id'), 'shop_cart_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_shop_cart_items_updated_at'), 'shop_cart_items', ['updated_at'], unique=False)
    op.create_table('shop_order_items',
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_purchase', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['shop_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['shop_products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_order_items_created_at'), 'shop_order_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_shop_order_items_order_id'), 'shop_order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_shop_order_items_product_id'), 'shop_order_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_shop_order_items_updated_at'), 'shop_order_items', ['updated_at'], unique=False)
    op.create_table('shop_wishlist_items',
    sa.Column('wishlist_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['shop_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wishlist_id'], ['shop_wishlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_wishlist_items_created_at'), 'shop_wishlist_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_shop_wishlist_items_product_id'), 'shop_wishlist_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_shop_wishlist_items_updated_at'), 'shop_wishlist_items', ['updated_at'], unique=False)
    op.create_index(op.f('ix_shop_wishlist_items_wishlist_id'), 'shop_wishlist_items', ['wishlist_id'], unique=False)
    op.create_table('vaccinations',
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('vaccine_name', sa.String(length=255), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('dose', sa.String(length=50), nullable=True),
    sa.Column('administration_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('certificate_url', sa.String(length=1024), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaccinations_administration_date'), 'vaccinations', ['administration_date'], unique=False)
    op.create_index(op.f('ix_vaccinations_created_at'), 'vaccinations', ['created_at'], unique=False)
    op.create_index(op.f('ix_vaccinations_pet_id'), 'vaccinations', ['pet_id'], unique=False)
    op.create_index(op.f('ix_vaccinations_updated_at'), 'vaccinations', ['updated_at'], unique=False)
    op.create_table('weight_histories',
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weight_histories_created_at'), 'weight_histories', ['created_at'], unique=False)
    op.create_index(op.f('ix_weight_histories_pet_id'), 'weight_histories', ['pet_id'], unique=False)
    op.create_index(op.f('ix_weight_histories_updated_at'), 'weight_histories', ['updated_at'], unique=False)
    op.create_table('ai_messages',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_messages_conversation_id'), 'ai_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_messages_created_at'), 'ai_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_messages_updated_at'), 'ai_messages', ['updated_at'], unique=False)
    op.create_table('ai_usage',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_conversation_id'), 'ai_usage', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_usage_created_at'), 'ai_usage', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_usage_updated_at'), 'ai_usage', ['updated_at'], unique=False)
    op.create_index(op.f('ix_ai_usage_user_id'), 'ai_usage', ['user_id'], unique=False)
    op.alter_column('pet_gallery_images', 'position',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_pet_gallery_images_created_at'), 'pet_gallery_images', ['created_at'], unique=False)
    op.create_index(op.f('ix_pet_gallery_images_updated_at'), 'pet_gallery_images', ['updated_at'], unique=False)
    op.alter_column('pets', 'sterilized',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pets', 'status',
               existing_type=mysql.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pets', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pets', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_pets_created_at'), 'pets', ['created_at'], unique=False)
    op.create_index(op.f('ix_pets_updated_at'), 'pets', ['updated_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_created_at'), 'refresh_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_updated_at'), 'refresh_tokens', ['updated_at'], unique=False)
    op.create_index(op.f('ix_user_preferences_created_at'), 'user_preferences', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_preferences_updated_at'), 'user_preferences', ['updated_at'], unique=False)
    op.create_index(op.f('ix_user_privacy_settings_created_at'), 'user_privacy_settings', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_privacy_settings_updated_at'), 'user_privacy_settings', ['updated_at'], unique=False)
    op.alter_column('users', 'timezone',
               existing_type=mysql.VARCHAR(length=64),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'language',
               existing_type=mysql.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_index(op.f('ix_verification_tokens_created_at'), 'verification_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_verification_tokens_updated_at'), 'verification_tokens', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_tokens_updated_at'), table_name='verification_tokens')
    op.drop_index(op.f('ix_verification_tokens_created_at'), table_name='verification_tokens')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.alter_column('users', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('users', 'language',
               existing_type=mysql.VARCHAR(length=10),
               server_default=sa.text("'en'"),
               existing_nullable=False)
    op.alter_column('users', 'timezone',
               existing_type=mysql.VARCHAR(length=64),
               server_default=sa.text("'UTC'"),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_privacy_settings_updated_at'), table_name='user_privacy_settings')
    op.drop_index(op.f('ix_user_privacy_settings_created_at'), table_name='user_privacy_settings')
    op.drop_index(op.f('ix_user_preferences_updated_at'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_created_at'), table_name='user_preferences')
    op.drop_index(op.f('ix_refresh_tokens_updated_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_created_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_pets_updated_at'), table_name='pets')
    op.drop_index(op.f('ix_pets_created_at'), table_name='pets')
    op.alter_column('pets', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('pets', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=False)
    op.alter_column('pets', 'status',
               existing_type=mysql.VARCHAR(length=16),
               server_default=sa.text("'ACTIVE'"),
               existing_nullable=False)
    op.alter_column('pets', 'sterilized',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.drop_index(op.f('ix_pet_gallery_images_updated_at'), table_name='pet_gallery_images')
    op.drop_index(op.f('ix_pet_gallery_images_created_at'), table_name='pet_gallery_images')
    op.alter_column('pet_gallery_images', 'position',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.drop_index(op.f('ix_ai_usage_user_id'), table_name='ai_usage')
    op.drop_index(op.f('ix_ai_usage_updated_at'), table_name='ai_usage')
    op.drop_index(op.f('ix_ai_usage_created_at'), table_name='ai_usage')
    op.drop_index(op.f('ix_ai_usage_conversation_id'), table_name='ai_usage')
    op.drop_table('ai_usage')
    op.drop_index(op.f('ix_ai_messages_updated_at'), table_name='ai_messages')
    op.drop_index(op.f('ix_ai_messages_created_at'), table_name='ai_messages')
    op.drop_index(op.f('ix_ai_messages_conversation_id'), table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index(op.f('ix_weight_histories_updated_at'), table_name='weight_histories')
    op.drop_index(op.f('ix_weight_histories_pet_id'), table_name='weight_histories')
    op.drop_index(op.f('ix_weight_histories_created_at'), table_name='weight_histories')
    op.drop_table('weight_histories')
    op.drop_index(op.f('ix_vaccinations_updated_at'), table_name='vaccinations')
    op.drop_index(op.f('ix_vaccinations_pet_id'), table_name='vaccinations')
    op.drop_index(op.f('ix_vaccinations_created_at'), table_name='vaccinations')
    op.drop_index(op.f('ix_vaccinations_administration_date'), table_name='vaccinations')
    op.drop_table('vaccinations')
    op.drop_index(op.f('ix_shop_wishlist_items_wishlist_id'), table_name='shop_wishlist_items')
    op.drop_index(op.f('ix_shop_wishlist_items_updated_at'), table_name='shop_wishlist_items')
    op.drop_index(op.f('ix_shop_wishlist_items_product_id'), table_name='shop_wishlist_items')
    op.drop_index(op.f('ix_shop_wishlist_items_created_at'), table_name='shop_wishlist_items')
    op.drop_table('shop_wishlist_items')
    op.drop_index(op.f('ix_shop_order_items_updated_at'), table_name='shop_order_items')
    op.drop_index(op.f('ix_shop_order_items_product_id'), table_name='shop_order_items')
    op.drop_index(op.f('ix_shop_order_items_order_id'), table_name='shop_order_items')
    op.drop_index(op.f('ix_shop_order_items_created_at'), table_name='shop_order_items')
    op.drop_table('shop_order_items')
    op.drop_index(op.f('ix_shop_cart_items_updated_at'), table_name='shop_cart_items')
    op.drop_index(op.f('ix_shop_cart_items_product_id'), table_name='shop_cart_items')
    op.drop_index(op.f('ix_shop_cart_items_created_at'), table_name='shop_cart_items')
    op.drop_index(op.f('ix_shop_cart_items_cart_id'), table_name='shop_cart_items')
    op.drop_table('shop_cart_items')
    op.drop_index(op.f('ix_medications_updated_at'), table_name='medications')
    op.drop_index(op.f('ix_medications_pet_id'), table_name='medications')
    op.drop_index(op.f('ix_medications_created_at'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_medical_records_updated_at'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_pet_id'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_created_at'), table_name='medical_records')
    op.drop_table('medical_records')
    op.drop_index(op.f('ix_health_documents_updated_at'), table_name='health_documents')
    op.drop_index(op.f('ix_health_documents_pet_id'), table_name='health_documents')
    op.drop_index(op.f('ix_health_documents_created_at'), table_name='health_documents')
    op.drop_table('health_documents')
    op.drop_index(op.f('ix_ai_conversations_user_id'), table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_updated_at'), table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_pet_id'), table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_created_at'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_shop_wishlists_user_id'), table_name='shop_wishlists')
    op.drop_index(op.f('ix_shop_wishlists_updated_at'), table_name='shop_wishlists')
    op.drop_index(op.f('ix_shop_wishlists_created_at'), table_name='shop_wishlists')
    op.drop_table('shop_wishlists')
    op.drop_index(op.f('ix_shop_products_updated_at'), table_name='shop_products')
    op.drop_index(op.f('ix_shop_products_name'), table_name='shop_products')
    op.drop_index(op.f('ix_shop_products_created_at'), table_name='shop_products')
    op.drop_index(op.f('ix_shop_products_category_id'), table_name='shop_products')
    op.drop_index(op.f('ix_shop_products_brand'), table_name='shop_products')
    op.drop_table('shop_products')
    op.drop_index(op.f('ix_shop_orders_user_id'), table_name='shop_orders')
    op.drop_index(op.f('ix_shop_orders_updated_at'), table_name='shop_orders')
    op.drop_index(op.f('ix_shop_orders_status'), table_name='shop_orders')
    op.drop_index(op.f('ix_shop_orders_created_at'), table_name='shop_orders')
    op.drop_table('shop_orders')
    op.drop_index(op.f('ix_shop_carts_user_id'), table_name='shop_carts')
    op.drop_index(op.f('ix_shop_carts_updated_at'), table_name='shop_carts')
    op.drop_index(op.f('ix_shop_carts_created_at'), table_name='shop_carts')
    op.drop_table('shop_carts')
    op.drop_index(op.f('ix_shop_categories_updated_at'), table_name='shop_categories')
    op.drop_index(op.f('ix_shop_categories_slug'), table_name='shop_categories')
    op.drop_index(op.f('ix_shop_categories_name'), table_name='shop_categories')
    op.drop_index(op.f('ix_shop_categories_created_at'), table_name='shop_categories')
    op.drop_table('shop_categories')
    # ### end Alembic commands ###
