"""
app/models/mixins.py

Reusable SQLAlchemy column mixins shared by every model.

Design decisions:
  - UUID string primary keys (36 chars) instead of auto-increment integers.
      * Prevents ID enumeration attacks (you cannot guess /users/2, /users/3).
      * Lets the application generate the ID before the INSERT (useful for
        building relationships and returning the ID without a round-trip).
  - Timezone-aware UTC timestamps generated in Python (``utcnow``) rather than
    ``server_default=func.now()`` so behaviour is identical on MySQL and the
    SQLite database used by the test-suite.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import DateTime, String
from sqlalchemy.orm import Mapped, mapped_column

from app.utils.datetime_helper import utcnow
from app.utils.uuid_helper import generate_uuid


class UUIDPrimaryKeyMixin:
    """Adds a UUID4 string primary key generated by the application."""

    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=generate_uuid,
        doc="UUID4 primary key (application-generated).",
    )


class TimestampMixin:
    """Adds ``created_at`` / ``updated_at`` UTC timestamps."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=utcnow,
        nullable=False,
        index=True,
        doc="Row creation time (UTC).",
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=utcnow,
        onupdate=utcnow,
        nullable=False,
        index=True,
        doc="Last modification time (UTC).",
    )
